config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'welcome#index'
  resources :users
  resources :listings do
    resources :reservations
  end
  get '/listings/confirm', to: 'listings#confirm', as: 'listing_confirm'

  get '/reservations/confirm/:reservation_id', to: 'reservations#confirm', as: 'reservation_confirm'
  
  resources :payments

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :reservations
  mount_uploaders :avatars, AvatarUploader


	def booked_dates
		dates_that_are_booked = []
		self.reservations.each do |reservation|
			reservations.each do |date|
				dates_that_are_booked << date
			end
		end
		return dates_that_are_booked
	end
  

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	
		
	
	def new

		@listing = Listing.new
	end

	def confirm
		@listing = Listing.new(listing_params)
		render 'confirm'
	end

	def create
		@listing = current_user.listings.new(listing_params)
		if @listing.save
			redirect_to listing_path(@listing.id)
			# render listing_path(@listing.id)
			# redirect_to '/listings/show/#{@listing.id}'
		else
			redirect_to new_listing_path 
			# render :new
			# render '/listings/new'
		end
		
	end

	def show
		@listing = Listing.find(params[:id])
		
	end

	def index
		listing_per_page = 5
		first_listing = 0 unless params[:page]
		first_listing = (params[:page].to_i-1) * listing_per_page
		listings = Listing.all
		@total_pages = Listing.all.count / listing_per_page
		if listings.count % listing_per_page > 0
			@total_pages += 1
		else
		end
		@listings = listings[first_listing...(first_listing + listing_per_page )]
	end

	

	private 

	def listing_params
		params.require(:listing).permit(:name, :location, :price, :num_of_people, :user_id, {avatars:[]})
	end

end


#With using active record assiociation you are able to link tables tgt (in your model file, u specify that Listing belongs_to :user, and User has_many :listings)

# This allows you to query data such as current_user.listings (returns u all the listing create by the current_user)
# You also can query who create a specific listing (listing = Listing.find(1) listing.user) #this returns u the user that created the specific listing

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/confirm.html.erb
<%=@listing.name%>

<%= form_for(@listing) do |f| %>
	<%= f.label @listing.name %>
	<%= f.hidden_field :name %>
	<br>
	<%= f.label @listing.location %>
	<%= f.hidden_field :location %>
	<br>
	<%= f.label @listing.num_of_people %>
	<%= f.hidden_field :num_of_people%>
	<br>
	<%= f.label @listing.price %>
	<%= f.hidden_field :price%>
	<br>
	<%= f.hidden_field :avatars, multiple: true %>
	<br>
	<%= f.submit "Confirm?"%>
<%end%>



<%= image_tag (@listing.avatars[0].url )  %>
todo print out confirmation order.
<a href="listings_path"><h1>Done</h1></a>

app/views/listings/index.html.erb
<% @listings.each do |listing| %>
	<%= image_tag (listing.avatars[0].url) unless listing.avatars[0].nil? %>
	<%= listing.name %><br>
	<%= listing.location%><br>
	<%= listing.price %><br>
	<%= link_to "BOOK NOW", new_listing_reservation_path(listing.id)%><br>
<%end%>

<div>
<% (1..@total_pages).each do |page|%>
<!-- alternative <a herf=""></a> -->
<%= link_to page, controller: "listings", action: "index", page: page%>&nbsp;
<%end%>	
</div>

app/views/listings/new.html.erb
<center>
<%= form_for @listing, url: listing_confirm_path do |f| %>
	<%= f.label :name%>
	<%= f.text_field :name %>
	<br>
	<%= f.label :location%>
	<%= f.text_field :location %>
	<br>
	<%= f.label :number_of_people_allowed%>
	<%= f.number_field :num_of_people%>
	<br>
	<%= f.label :price%>
	<%= f.number_field :price%>
	<br>
	<%= f.file_field :avatars, multiple: true %>
	<br>
	<%= f.submit %>
<%end%>
</center>

app/views/listings/show.html.erb
Show page