config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  root 'welcome#index'
  resources :users
  resources :listings do
    resources :reservations
  end
  get '/listings/confirm', to: 'listings#confirm', as: 'listing_confirm'

  get '/reservations/confirm/:reservation_id', to: 'reservations#confirm', as: 'reservation_confirm'
  
  resources :payments

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing
	has_many :payments

	def dates
		(check_in_date..check_out_date).to_a
	end

	def overlapping_date(booked_dates)
		dates & booked_dates
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def new
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.new
	end

	def create
		@listing = Listing.find(params[:listing_id])
		@reservation = current_user.reservations.new(reservation_params)
		@reservation.listing_id = @listing.id
		@host = "noprogrammerlikeme@gmail.com"
		booked_dates = @listing.booked_dates
		if   @reservation.overlapping_date(booked_dates).empty? && @reservation.save
			#this checks if the booked_dates are empty, if is empty then it will create a new reservation
			#once im able to create a new reservation, i would need to add my listing_id into my reservation as i only have user_id for now (current_user.reservations)
			 @reservation.update(listing_id: @listing.id)
			 ReservationMailer.notification_email(current_user.email, @host, @reservation.listing.id, @reservation.id).deliver_now
			 ReservationJob.perform_later(current_user.email, @host, @reservation.listing.id, @reservation.id)
			redirect_to listing_reservation_path(@listing.id, @reservation.id)
			
		else
			flash[:notice] = "dates are not available on #{@reservation.overlapping_dates(booked_dates)}"

			redirect_to new_reservation_path
		end
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	

	def index
	end 

	def confirm
		@reservation = Reservation.find(params[:reservation_id])
	end

	private 

	def reservation_params
		params.require(:reservation).permit( :listing_id, :user_id, :price, :check_in_date, :check_out_date)
	end




end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
confirmation page for reservation
<!-- <center>
don't use form_for cause it will prompt you to make an action called update!!!!!
<%= form_for([@reservation.listing, @reservation]) do |f|%>
	name <%= f.label @reservation.listing.name%>
	
	<br>
	location <%= f.label @reservation.listing.location%>
	
	<br>
	number of people <%= f.label @reservation.listing.num_of_people%>
	
	<br>
	check in date <%= f.label @reservation.check_in_date%>
	
	<br>
	check out date <%= f.label @reservation.check_out_date%>
	
	<br>
	price <%= f.label @reservation.listing.price %>
	<br>
	<%= f.submit "confirm"%>
	<br>
<% end%>
</center>>
 -->
<!-- # <%=@reservation.listing.name%>

# location <%=@reservation.listing.location%><br>
# number of people <%=@reservation.listing.num_of_people%><br>
# check in <%=@reservation.check_in_date%><br>
# check out <%=@reservation.check_out_date%><br>
# total price <%=@reservation.listing.price%><br>
# </center>

# name
# location
# num_of_people
# checkindate
# checkoutdate
# price
 -->
<!-- link_to "confirm", listing_confirm_path -->
<center>
location <%=@reservation.listing.name%>
<br>
number of people <%=@reservation.listing.num_of_people%>
<br>
check in <%=@reservation.check_in_date%>
<br>
check out <%=@reservation.check_out_date%>
<br>
total price <%=@reservation.listing.price%>
<br>
<%=link_to "confirm", listing_reservations_path(@reservation.listing.id)%>
</center>

app/views/reservations/new.html.erb
<h1>Reservation Page</h1> 

<%= form_for [@listing, @reservation]  do |form| %>  
  <%=form.label :number_of_people%>
  <%=form.number_field :user_id%>
 <!--  < %=  form.hidden_field :listing_id , :value => @listing.id%> --> <!-- this is for normal routes
  -->
  <br>
  <%=form.hidden_field :price, value: @listing.price %>
  <br>
  <%=form.label :check_in_date%>
  <%=form.date_field :check_in_date, placeholder:  "dd/mm/yy"%>
  <br>
  <%=form.label :check_out_date%>
  <%=form.date_field :check_out_date, placeholder: "dd/mm/yy"%>
  <br>
  price per day <%=@listing.price%>
  <br>
  location at <%=@listing.location%>
  <br>

  <%= form.submit %>
<%end%>

<!-- url: listing_reservations_path() do this for nested routes on line 3 -->

app/views/reservations/show.html.erb
<h3>Your Reservation</h3>

<ul class="list-group">
  <li class="list-group-item">
    <p>Listing name: <%= link_to @reservation.listing.name, listing_path(@reservation.listing) %></p>
    <p>No. of Guest: <%= @reservation.listing.num_of_people%> </p>
    <p>Location: <%= @reservation.listing.location %> </p>
    <p>Check-in Date: <%= @reservation.check_in_date %></p>

    <p>Checkout Date: <%= @reservation.check_out_date %></p>
    <P>price <%=@reservation.price%></P>

    <strong>Payment Status:</strong>
      <% if @reservation.payments.where(status: :authorized).count == 0%>
      <span class="btn btn-danger"> NOT PAID </span>

       <%= link_to 'Pay Now' , new_payment_path + "?id=" + @reservation.id.to_s, class: "btn btn-warning"  %>
      <% else %>
        <span class="btn btn-success">PAID</span>
      <% end %>
  </li>
</ul>

<!-- replace payments with price -->


<!-- < % Reservation.where(user_id: current_user.id).each do |r| %>
<div id="cancel_booking_< %=r.id%>">
<a href= "/listings/< %=r.listing_id%>">< %= Listing.find(r.listing_id).title %></a><br>
Start date: < %= r.start_date.strftime("%v") %><br>
End date: < %= r.end_date.strftime("%v") %><br>
Duration: < %= r.stay_duration %> days<br>
Total Price: $< %= r.total_price %>.00 <br> -->